Memory leak fix when content size header is 0
autinitysystems/Compress-LZ4Frame pull request #5
Opened 2018-01-18 15:07 UTC by jpiautinity

This fixes a small memory leak for cases in which the content size header is 0 and no error occurs.
The LZ4 library has been updated also.

2018-01-18 15:43 UTC, Drako commented
wow, in all the error cases the memory is freed, but I missed to do so in the standard path
nice find

2018-01-18 15:50 UTC, Drako requested changes
Please also add your changes to the changelog (Changes file) und NEXT
when doing "dzil release" NEXT will be replaced with the version number you wrote into dist.ini

also please update the copyright in the README.md as this still shows 2015-2017.

2018-01-18 21:25 UTC, Drako approved these changes

2018-01-19 08:46 UTC, Drako commented
@jpiautinity will you do the merge and CPAN release or shall I handle that?

2018-01-19 08:57 UTC, jpiautinity commented
I will handle the rest. Thank you for taking the time to review the code.

2018-01-19 08:58 UTC, merged

2018-01-19 08:58 UTC, Drako commented
it has been my pleasure.